package com.campussocialmedia.campussocialmedia.entity;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName =  "Comment")
public class Comment implements Serializable{
    
    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private String userName;
    private String comment;
    private String timeStamp;
    private String commentID;
    private String postID;

    @DynamoDBHashKey(attributeName = "commentID")
    @DynamoDBAutoGeneratedKey
    public String getCommentID() {
        return commentID;
    }

    public void setCommentID(String commentID) {
        this.commentID = commentID;
    }
    
    @DynamoDBAttribute
    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    @DynamoDBAttribute
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    public String getTimeStamp() {
        return timeStamp;
    }

    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }
    
    
    public Comment(String userName, String comment) {
        this.userName = userName;
        this.comment = comment;
    }

    
   
    public Comment() {
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "PostIndex")
    public String getPostID() {
        return postID;
    }

    public void setPostID(String postID) {
        this.postID = postID;
    }

    @Override
    public String toString() {
        return "Comment [comment=" + comment + ", commentID=" + commentID + ", postID=" + postID + ", timeStamp="
                + timeStamp + ", userName=" + userName + "]";
    }
    
            
}
